graham = User.create(username: 'graham')
adam = User.create(username: 'adam')
kailey = User.create(username: 'kailey')

Game.create(user: graham, score: 10, game_type: "add")
Game.create(user: graham, score: 10, game_type: "add")
Game.create(user: graham, score: 10, game_type: "add")
Game.create(user: graham, score: 10, game_type: "sub")
Game.create(user: graham, score: 10, game_type: "sub")
Game.create(user: graham, score: 10, game_type: "sub")
Game.create(user: graham, score: 10, game_type: "mult")
Game.create(user: graham, score: 10, game_type: "mult")
Game.create(user: graham, score: 10, game_type: "mult")

Game.create(user: adam, score: 10, game_type: "add")
Game.create(user: adam, score: 10, game_type: "add")
Game.create(user: adam, score: 10, game_type: "add")
Game.create(user: adam, score: 10, game_type: "sub")
Game.create(user: adam, score: 10, game_type: "sub")
Game.create(user: adam, score: 10, game_type: "sub")
Game.create(user: adam, score: 10, game_type: "mult")
Game.create(user: adam, score: 10, game_type: "mult")
Game.create(user: adam, score: 10, game_type: "mult")

Game.create(user: kailey, score: 10, game_type: "add")
Game.create(user: kailey, score: 10, game_type: "add")
Game.create(user: kailey, score: 10, game_type: "add")
Game.create(user: kailey, score: 10, game_type: "sub")
Game.create(user: kailey, score: 10, game_type: "sub")
Game.create(user: kailey, score: 10, game_type: "sub")
Game.create(user: kailey, score: 10, game_type: "mult")
Game.create(user: kailey, score: 10, game_type: "mult")
Game.create(user: kailey, score: 10, game_type: "mult")

