graham = User.create(username: 'grahamf')
adam = User.create(username: 'adamf')
david = User.create(username: 'davidf')
kailey = User.create(username: 'kaileyl')
christina = User.create(username: 'christinap')
heejae = User.create(username: 'heejaeh')

Game.create(score: 50, user: graham)
Game.create(score: 10, user: adam)
Game.create(score: 2, user: david)
Game.create(score: 70, user: kailey)
Game.create(score: 30, user: christina)
Game.create(score: 15, user: heejae)

Game.create(score: 50, user: graham)
Game.create(score: 10, user: adam)
Game.create(score: 2, user: david)
Game.create(score: 70, user: kailey)
Game.create(score: 30, user: christina)
Game.create(score: 15, user: heejae)

Game.create(score: 50, user: graham)
Game.create(score: 10, user: adam)
Game.create(score: 2, user: david)
Game.create(score: 70, user: kailey)
Game.create(score: 30, user: christina)
Game.create(score: 15, user: heejae)
